service:
  name: chrome-store-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getExtensionMetadata:
    handler: handler.handler
    events:
      - http:
          method: get
          path: extension
          cors: true
