import { ScreenshotImage, ScreenshotVideo } from './screenshot';

export type FormattedExtensionData = {
    id: string,
    name: string,
    developer_display_name: string,
    icon_small: string,
    promotional_tile_small: string,
    promotional_tile_large: string,
    description: string,
    category: string,
    permalink: string,
    avg_rating: number,
    ratings: number,
    weekly_users: string,
    icon_large: string,
    price: string,
    websites: string,
    version: string,
    developer_details: [string|null, string|null, string|null],
    last_updated: string,
    size: string,
    support_url: string,
    reviews_url: string,
    schema: string,
    languages: string[],
    type: string,
    website_link: string,
    detailed_description: string,
    screenshots: Array<ScreenshotImage|ScreenshotVideo>,
    reviews: string,
    owner: string,
};
